### PR TITLE
Fix reload data

### PR DESCRIPTION
**Pull request by liuleirain**

### CODE REVIEW

**Review by liuleirain — COMMENTED** [review]
Fix reload data

**Review by liuleirain — COMMENTED** [review]
Fix reload data

**Review by liuleirain — COMMENTED** [review]
Fix reload data

**Review by liuleirain — COMMENTED** [review]
Fix reload data

**Comment by liuleirain** [comment]
Fix reload data

**Review by liuleirain — COMMENTED** [review]
Fix reload data

**Comment by bernatvadell** [comment]
Thank you bro, keep working!

**Pull request merged**
