### PR TITLE
New items

### PR DESCRIPTION
**Pull request by heian1380**
The text content has not yet been translated

### CODE REVIEW

**Comment by heian1380** [comment]
~K C7I7I6B3 {W4W_W4WGA9

This can only translate the skill content, the file I uploaded is an item file
@bernatvadell

**Comment by periko92** [comment]
> ~K C7I7I6B3 {W4W_W4WGA9
> 
> This can only translate the skill content, the file I uploaded is an item file @bernatvadell
CopyContent also has Items section, if it's throwing exception, its because you will need to add "more cases" into the code (new strings on chinese files)
image

**Comment by heian1380** [comment]
The documents have been translated and ready to be pulled @periko92 @bernatvadell

**Comment by bernatvadell** [comment]
Nice: 
[2022-10-06 13:58:50]: GameItems Loaded, Total: 1953, Elapsed: 1473ms

**Pull request merged**
